// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n';
import type { GenericNumberParameter, GenericStringParameter } from './types';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en' | 'fr' | 'nl';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

export type RoutesTranslations = {
    href: RequiredParams<'0'>;
    public: {
        logIn: string;
    };
    protected: {
		logOut: string;
		dashboard: string;
		users: string;
		roles: string;
		permissions: string;
		projects: string;
		tasks: string;
		profile: string;
	}
};

export type MenusTranslations = {
	sidebar: {
		dashboard: string;
		users: string;
		permissions: string;
		roles: string;
		projects: string;
		tasks: string;
		noItemsFoundMessage: string;
	}
};

export type PagesTranslations = {};

export type WarningsTranslations = {};

export type ErrorsTranslations = {
    required: string;
    required_select: string;
    required_date: string;
    invalid_date: string;
    invalid_form: string;
    invalid_email: string;
    invalid_password: string;
    invalid_combination: string;
    min_characters: string;
    max_characters: string;
    min_value: string;
    max_value: string;
    no_something_found: string;
    internal_server_error: string;
    email_not_found: string;
    email_address_already_in_use: string;
    no_data_found: string;
    no_entity_found: string;
    no_information: string;
};

export type FieldsTranslations = {
    fullName: {
        text: string;
    };
	firstName: {
		text: string;
	};
	lastName: {
		text: string;
	};
	password: {
		text: string;
		hidePassword: string;
		showPassword: string;
		forgotYourPassword: string;
	};
	email: {
		text: string;
	};
	search: {
		text: string;
	};
	phone: {
		text: string;
	};
};

export type ButtonsOrLinksTranslations = {};

export type ComponentsTranslations = {
    modal: {
        edit: string;
        add: string;
    };
    table: {
        actions: string;
    };
};

type RootTranslation = {
    routes: RoutesTranslations;
    menus: MenusTranslations;
    pages: PagesTranslations;
    warnings: WarningsTranslations;
    errors: ErrorsTranslations;
    fields: FieldsTranslations;
    buttonsOrLinks: ButtonsOrLinksTranslations;
    components: ComponentsTranslations;
};

export type TranslationFunctions = {
    routes: {
        href: (arg0: unknown) => LocalizedString;
        public: {
            logIn: () => LocalizedString;
        };
        protected: {
            logOut: () => LocalizedString;
			dashboard: () => LocalizedString;
			users: () => LocalizedString;
			roles: () => LocalizedString;
			permissions: () => LocalizedString;
			projects: () => LocalizedString;
			tasks: () => LocalizedString;
			profile: () => LocalizedString;
        };
    };
	menus: {
		sidebar: {
			dashboard: () => LocalizedString;
			users: () => LocalizedString;
			permissions: () => LocalizedString;
			roles: () => LocalizedString;
			projects: () => LocalizedString;
			tasks: () => LocalizedString;
			noItemsFoundMessage: () => LocalizedString;
		};
	},
	pages: {},
	warnings: {};
	errors: {
		required: ({field}: GenericStringParameter) => LocalizedString;
        required_select: () => LocalizedString;
        required_date: () => LocalizedString;
        invalid_date: () => LocalizedString;
        invalid_form: () => LocalizedString;
        invalid_email: () => LocalizedString;
        invalid_password: () => LocalizedString;
        invalid_combination: () => LocalizedString;
        min_characters: ({ number }: GenericNumberParameter) => LocalizedString;
        max_characters: ({ number }: GenericNumberParameter) => LocalizedString;
        min_value: ({ number }: GenericNumberParameter) => LocalizedString;
        max_value: ({ number }: GenericNumberParameter) => LocalizedString;
        no_something_found: ({ something }: GenericStringParameter) => LocalizedString;
        internal_server_error: () => LocalizedString;
        email_not_found: () => LocalizedString;
        security_code_not_found: () => LocalizedString;
        security_code_expired: () => LocalizedString;
        email_address_already_in_use: () => LocalizedString;
        no_data_found: () => LocalizedString;
        no_entity_found: ({ entity }: GenericStringParameter) => LocalizedString;
        no_information: () => LocalizedString;
    };
    fields: {
        fullName: {
            text: () => LocalizedString;
        };
		firstName: {
			text: () => LocalizedString;
		};
		lastName: {
			text: () => LocalizedString;
		};
		password: {
			text: () => LocalizedString;
			hidePassword: () => LocalizedString;
			showPassword: () => LocalizedString;
			forgotYourPassword: () => LocalizedString;
		};
		email: {
			text: () => LocalizedString;
		};
		search: {
			text: () => LocalizedString;
		};
		phone: {
			text: () => LocalizedString;
		};
    };
    buttonsOrLinks: {};
    components: {
        modal: {
            edit: ({ something }: GenericStringParameter) => LocalizedString;
            add: ({ something }: GenericStringParameter) => LocalizedString;
        };
        table: {
            actions: () => LocalizedString;
        };
    };
};
export type Formatters = {};
